-- 215_t_grow2_referral_loop_REHEARSAL.sql
--
-- GENERATED by supabase/recon/t-grow2-build-rehearsal.LOCAL.py from
-- supabase/recon/215_REHEARSAL.template.sql. Edit the template, then rebuild;
-- the migration body and its guard are spliced in, never retyped.
--
-- Rehearsal for supabase/migrations/215_t_grow2_referral_loop.sql. Run in the
-- Supabase SQL editor. Everything through the ROLLBACK is inside
-- BEGIN ... ROLLBACK; production is not modified. ONE result set.
--
-- Part A  the migration body INCLUDING ITS DO GUARD, spliced verbatim; then the
--         catalog and the scaffolding.
-- Part B  pass_leads.lead_ref_code from both directions. B1 (an anonymous
--         claim with no code, i.e. the live pass form) and B3 (the /api/pase
--         write) are the POSITIVE arms: a FAIL there means this breaks claims.
-- Part C  referrals. C1 (a user creating their own code row, i.e. the
--         /referral page) and C3 (the server linking a signup) are POSITIVE.
--         C2 is the forgery this migration closes.
-- Part D  215's own guard, unmutated (D0) and against four mutations, each
--         asserting the mutation LANDED first.
-- Part E  the bug reverted: drop the new referrals policy and show a user CAN
--         then forge a referral. That is the premise, measured.
-- Part F  identity and baseline.
-- Part G  nothing escaped -- OUTSIDE THE TRANSACTION.
--
-- THROWAWAYS ONLY. Two auth.users rows (reh-215-*@example.com) through the
-- real handle_new_user path, and a CLONE of a featured_partners row with a new
-- id, a reh- slug, user_id NULL, status 'paused' (211's construction, for the
-- reason 211 gives: never exercise a pass flow against a real gym's record).
-- The admin is borrowed only to own nothing; no real row is written.
--
-- Refusal arms match SQLSTATE AND the object that refused, where the message
-- names one, because RLS refusals are all 42501.

BEGIN;

-- ══════════════════════════════════════════════════════════════════════════
-- PART A: the migration body, spliced verbatim from
--         supabase/migrations/215_t_grow2_referral_loop.sql
--         (its BEGIN/COMMIT and its migrations_applied INSERT omitted)
-- ══════════════════════════════════════════════════════════════════════════

-- ── 1. pass_leads.lead_ref_code ─────────────────────────────────────────────
ALTER TABLE public.pass_leads ADD COLUMN IF NOT EXISTS lead_ref_code text;

COMMENT ON COLUMN public.pass_leads.lead_ref_code IS
  'T-GROW2. The code this lead shares in "Trae a un amigo" links (?ref=CODE). '
  'Six characters, no 0/O/1/I. Generated server side by /api/pase; refused from '
  'any client insert. A friend who claims through the link carries it as attr_ref. '
  'Deliberately NOT the pass_code, which is the door handle and stays private.';

ALTER TABLE public.pass_leads DROP CONSTRAINT IF EXISTS pass_leads_lead_ref_code_shape;
ALTER TABLE public.pass_leads
  ADD CONSTRAINT pass_leads_lead_ref_code_shape
  CHECK (lead_ref_code IS NULL OR lead_ref_code ~ '^[A-HJ-NP-Z2-9]{6}$');

CREATE UNIQUE INDEX IF NOT EXISTS pass_leads_lead_ref_code_key
  ON public.pass_leads (lead_ref_code) WHERE lead_ref_code IS NOT NULL;

DROP POLICY IF EXISTS "Lead referral code is server only" ON public.pass_leads;
CREATE POLICY "Lead referral code is server only" ON public.pass_leads
  AS RESTRICTIVE
  FOR INSERT
  WITH CHECK (lead_ref_code IS NULL);

-- ── 2. One credit per referred person ───────────────────────────────────────
CREATE UNIQUE INDEX IF NOT EXISTS referrals_one_credit_per_referred
  ON public.referrals (referred_id) WHERE referred_id IS NOT NULL;

-- ── 3. Clients create only code rows ────────────────────────────────────────
DROP POLICY IF EXISTS "Clients create only code rows" ON public.referrals;
CREATE POLICY "Clients create only code rows" ON public.referrals
  AS RESTRICTIVE
  FOR INSERT
  WITH CHECK (referred_id IS NULL);

-- ── 4. Assert the end state ─────────────────────────────────────────────────
DO $$
DECLARE
  v_row record;
  v_name text;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid = 'public.pass_leads'::regclass
                  AND attname = 'lead_ref_code' AND NOT attisdropped AND atttypid = 'text'::regtype) THEN
    RAISE EXCEPTION '215 ABORTED: pass_leads.lead_ref_code is missing or is not text.';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.pass_leads'::regclass
                  AND conname = 'pass_leads_lead_ref_code_shape' AND contype = 'c' AND convalidated) THEN
    RAISE EXCEPTION '215 ABORTED: CHECK pass_leads_lead_ref_code_shape is missing or not validated.';
  END IF;

  -- Both indexes UNIQUE and PARTIAL. A non-partial index on referred_id would
  -- treat the code rows' NULLs as distinct and pass today, then mean something
  -- else if anyone ever made the column NOT NULL; asserting the predicate says
  -- what this index is for.
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND tablename = 'pass_leads'
                  AND indexname = 'pass_leads_lead_ref_code_key'
                  AND indexdef ILIKE 'CREATE UNIQUE INDEX%' AND indexdef ILIKE '%WHERE%lead_ref_code IS NOT NULL%') THEN
    RAISE EXCEPTION '215 ABORTED: pass_leads_lead_ref_code_key is missing, not unique, or not partial.';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND tablename = 'referrals'
                  AND indexname = 'referrals_one_credit_per_referred'
                  AND indexdef ILIKE 'CREATE UNIQUE INDEX%' AND indexdef ILIKE '%WHERE%referred_id IS NOT NULL%') THEN
    RAISE EXCEPTION '215 ABORTED: referrals_one_credit_per_referred is missing, not unique, or not partial.';
  END IF;

  -- The two new policies: RESTRICTIVE, FOR INSERT, every role, the right clause.
  FOR v_row IN
    SELECT * FROM (VALUES
      ('pass_leads', 'Lead referral code is server only', 'lead_ref_code IS NULL'),
      ('referrals',  'Clients create only code rows',     'referred_id IS NULL')
    ) AS t(tbl, pol, clause)
  LOOP
    IF NOT EXISTS (SELECT 1 FROM pg_policies p
                    WHERE p.schemaname = 'public' AND p.tablename = v_row.tbl AND p.policyname = v_row.pol
                      AND p.permissive = 'RESTRICTIVE' AND p.cmd = 'INSERT' AND p.roles::text = '{public}'
                      AND position(v_row.clause IN p.with_check) > 0) THEN
      RAISE EXCEPTION '215 ABORTED: policy "%" on % is missing, not RESTRICTIVE FOR INSERT for all roles, or lacks "%".',
        v_row.pol, v_row.tbl, v_row.clause;
    END IF;
  END LOOP;

  -- Nothing else was touched. Named, not counted: a count is satisfied by one
  -- policy being replaced by another.
  FOREACH v_name IN ARRAY ARRAY['Anyone can claim a pass', 'Admins manage pass leads', 'Partner reads own leads',
                                'Program columns are server only', 'Attribution columns are server only'] LOOP
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'pass_leads'
                    AND policyname = v_name) THEN
      RAISE EXCEPTION '215 ABORTED: pass_leads policy "%" is gone; this file must not have changed it.', v_name;
    END IF;
  END LOOP;
  FOREACH v_name IN ARRAY ARRAY['Users can insert referrals', 'Users can read own referrals',
                                'Users can view own referrals'] LOOP
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'referrals'
                    AND policyname = v_name) THEN
      RAISE EXCEPTION '215 ABORTED: referrals policy "%" is gone; this file must not have changed it.', v_name;
    END IF;
  END LOOP;

  -- The service role, the only writer of both new things, can still write.
  IF NOT has_table_privilege('service_role', 'public.referrals', 'INSERT')
     OR NOT has_table_privilege('service_role', 'public.pass_leads', 'INSERT') THEN
    RAISE EXCEPTION '215 ABORTED: service_role cannot INSERT referrals or pass_leads.';
  END IF;

  RAISE NOTICE '215: lead referral codes, one credit per referred person, client forgery closed.';
END $$;

-- ══════════════════════════════════════════════════════════════════════════
-- PARTS B to F
-- ══════════════════════════════════════════════════════════════════════════
CREATE TEMP TABLE reh_probe (seq integer, check_name text, detail text, passed boolean);

DO $outer$
DECLARE
  v_guard text := $guard$DO $$
DECLARE
  v_row record;
  v_name text;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid = 'public.pass_leads'::regclass
                  AND attname = 'lead_ref_code' AND NOT attisdropped AND atttypid = 'text'::regtype) THEN
    RAISE EXCEPTION '215 ABORTED: pass_leads.lead_ref_code is missing or is not text.';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.pass_leads'::regclass
                  AND conname = 'pass_leads_lead_ref_code_shape' AND contype = 'c' AND convalidated) THEN
    RAISE EXCEPTION '215 ABORTED: CHECK pass_leads_lead_ref_code_shape is missing or not validated.';
  END IF;

  -- Both indexes UNIQUE and PARTIAL. A non-partial index on referred_id would
  -- treat the code rows' NULLs as distinct and pass today, then mean something
  -- else if anyone ever made the column NOT NULL; asserting the predicate says
  -- what this index is for.
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND tablename = 'pass_leads'
                  AND indexname = 'pass_leads_lead_ref_code_key'
                  AND indexdef ILIKE 'CREATE UNIQUE INDEX%' AND indexdef ILIKE '%WHERE%lead_ref_code IS NOT NULL%') THEN
    RAISE EXCEPTION '215 ABORTED: pass_leads_lead_ref_code_key is missing, not unique, or not partial.';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND tablename = 'referrals'
                  AND indexname = 'referrals_one_credit_per_referred'
                  AND indexdef ILIKE 'CREATE UNIQUE INDEX%' AND indexdef ILIKE '%WHERE%referred_id IS NOT NULL%') THEN
    RAISE EXCEPTION '215 ABORTED: referrals_one_credit_per_referred is missing, not unique, or not partial.';
  END IF;

  -- The two new policies: RESTRICTIVE, FOR INSERT, every role, the right clause.
  FOR v_row IN
    SELECT * FROM (VALUES
      ('pass_leads', 'Lead referral code is server only', 'lead_ref_code IS NULL'),
      ('referrals',  'Clients create only code rows',     'referred_id IS NULL')
    ) AS t(tbl, pol, clause)
  LOOP
    IF NOT EXISTS (SELECT 1 FROM pg_policies p
                    WHERE p.schemaname = 'public' AND p.tablename = v_row.tbl AND p.policyname = v_row.pol
                      AND p.permissive = 'RESTRICTIVE' AND p.cmd = 'INSERT' AND p.roles::text = '{public}'
                      AND position(v_row.clause IN p.with_check) > 0) THEN
      RAISE EXCEPTION '215 ABORTED: policy "%" on % is missing, not RESTRICTIVE FOR INSERT for all roles, or lacks "%".',
        v_row.pol, v_row.tbl, v_row.clause;
    END IF;
  END LOOP;

  -- Nothing else was touched. Named, not counted: a count is satisfied by one
  -- policy being replaced by another.
  FOREACH v_name IN ARRAY ARRAY['Anyone can claim a pass', 'Admins manage pass leads', 'Partner reads own leads',
                                'Program columns are server only', 'Attribution columns are server only'] LOOP
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'pass_leads'
                    AND policyname = v_name) THEN
      RAISE EXCEPTION '215 ABORTED: pass_leads policy "%" is gone; this file must not have changed it.', v_name;
    END IF;
  END LOOP;
  FOREACH v_name IN ARRAY ARRAY['Users can insert referrals', 'Users can read own referrals',
                                'Users can view own referrals'] LOOP
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'referrals'
                    AND policyname = v_name) THEN
      RAISE EXCEPTION '215 ABORTED: referrals policy "%" is gone; this file must not have changed it.', v_name;
    END IF;
  END LOOP;

  -- The service role, the only writer of both new things, can still write.
  IF NOT has_table_privilege('service_role', 'public.referrals', 'INSERT')
     OR NOT has_table_privilege('service_role', 'public.pass_leads', 'INSERT') THEN
    RAISE EXCEPTION '215 ABORTED: service_role cannot INSERT referrals or pass_leads.';
  END IF;

  RAISE NOTICE '215: lead referral codes, one credit per referred person, client forgery closed.';
END $$;$guard$;

  k_ref     uuid := gen_random_uuid();   -- the referrer
  k_new     uuid := gen_random_uuid();   -- the referred newcomer
  k_partner uuid := gen_random_uuid();
  k_slug    constant text := 'reh215-throwaway-pass';
  k_code    constant text := 'TRIBE-RH215';
  k_consent constant text := 'Autorizo el tratamiento de mis datos para esta clase de prueba.';
  v_n integer; v_txt text; v_id uuid;

  a1_state text := '(never ran)'; a1_ok boolean := false;
  a2_state text := '(never ran)'; a2_ok boolean := false;
  f3_state text := '(never ran)'; f3_ok boolean := false;
  b1_state text := '(never ran)'; b1_ok boolean := false;
  b2_state text := '(never ran)'; b2_ok boolean := false;
  b3_state text := '(never ran)'; b3_ok boolean := false;
  b4_state text := '(never ran)'; b4_ok boolean := false;
  b5_state text := '(never ran)'; b5_ok boolean := false;
  c1_state text := '(never ran)'; c1_ok boolean := false;
  c2_state text := '(never ran)'; c2_ok boolean := false;
  c3_state text := '(never ran)'; c3_ok boolean := false;
  c4_state text := '(never ran)'; c4_ok boolean := false;
  d0_state text := '(never ran)'; d0_ok boolean := false;
  d1_state text := '(never ran)'; d1_ok boolean := false;
  d2_state text := '(never ran)'; d2_ok boolean := false;
  d3_state text := '(never ran)'; d3_ok boolean := false;
  d4_state text := '(never ran)'; d4_ok boolean := false;
  e1_state text := '(never ran)'; e1_ok boolean := false;
  f1_state text := '(never ran)'; f1_ok boolean := false;
  f2_state text := '(never ran)'; f2_ok boolean := false;
BEGIN

-- A1: the catalog, independently of the guard.
SELECT count(*) INTO v_n FROM pg_indexes
 WHERE schemaname = 'public'
   AND indexname IN ('pass_leads_lead_ref_code_key', 'referrals_one_credit_per_referred')
   AND indexdef ILIKE 'CREATE UNIQUE INDEX%' AND indexdef ILIKE '%WHERE%';
a1_state := v_n || ' of 2 partial unique indexes; '
  || (SELECT count(*) FROM pg_policies WHERE schemaname = 'public' AND permissive = 'RESTRICTIVE'
       AND policyname IN ('Lead referral code is server only', 'Clients create only code rows'))
  || ' of 2 restrictive policies; lead_ref_code column '
  || CASE WHEN EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid = 'public.pass_leads'::regclass
                        AND attname = 'lead_ref_code' AND NOT attisdropped) THEN 'present' ELSE 'ABSENT' END;
a1_ok := a1_state = '2 of 2 partial unique indexes; 2 of 2 restrictive policies; lead_ref_code column present';

-- A2: scaffolding. Two signups through the real path, and a throwaway partner.
BEGIN
  INSERT INTO auth.users (id, email, created_at, raw_user_meta_data)
  VALUES (k_ref, 'reh-215-ref@example.com', now(), '{"name":"Reh Referrer"}'::jsonb),
         (k_new, 'reh-215-new@example.com', now(), '{"name":"Reh Newcomer"}'::jsonb);
  INSERT INTO public.featured_partners
  SELECT r.*
    FROM public.featured_partners fp
    CROSS JOIN LATERAL jsonb_populate_record(
      NULL::public.featured_partners,
      to_jsonb(fp.*) || jsonb_build_object(
        'id', k_partner, 'slug', k_slug, 'user_id', NULL, 'pass_active', true,
        'business_name', 'REHEARSAL THROWAWAY (roll back)', 'status', 'paused')
    ) AS r
   ORDER BY fp.created_at NULLS LAST
   LIMIT 1;
  SELECT count(*) INTO v_n FROM public.users WHERE id IN (k_ref, k_new);
  a2_state := v_n || ' of 2 throwaway users via handle_new_user; pass_is_active='
    || coalesce(public.pass_is_active(k_partner, k_slug)::text, 'NULL');
  a2_ok := v_n = 2 AND public.pass_is_active(k_partner, k_slug);
EXCEPTION WHEN OTHERS THEN
  a2_state := 'scaffolding failed: ' || SQLSTATE || ' ' || SQLERRM; a2_ok := false;
END;

f3_state := 'current_user=' || current_user || ' session_user=' || session_user
  || ' auth.uid()=' || coalesce(auth.uid()::text, 'NULL');
f3_ok := auth.uid() IS NULL;

-- ── PART B: pass_leads.lead_ref_code ──────────────────────────────────────

-- B1: POSITIVE. An anonymous claim with no code: the live pass form.
BEGIN
  PERFORM set_config('request.jwt.claims', NULL, true);
  SET LOCAL ROLE anon;
  BEGIN
    INSERT INTO public.pass_leads (slug, partner_id, name, whatsapp, email, pass_code, consent_text)
    VALUES (k_slug, k_partner, 'Reh Anon Plain', '+573001234567', 'reh-b1@example.com', 'RH-BONE', k_consent);
    b1_state := 'anon claimed a pass with no lead_ref_code, as the live form does'; b1_ok := true;
  EXCEPTION WHEN OTHERS THEN
    b1_state := 'REFUSED the live pass form: ' || SQLSTATE || ' ' || SQLERRM;
  END;
  RESET ROLE;
EXCEPTION WHEN OTHERS THEN
  RESET ROLE; b1_state := 'scaffolding failed: ' || SQLERRM; b1_ok := false;
END;

-- B2: an anonymous claim that brings its own lead_ref_code is refused.
BEGIN
  PERFORM set_config('request.jwt.claims', NULL, true);
  SET LOCAL ROLE anon;
  BEGIN
    INSERT INTO public.pass_leads (slug, partner_id, name, whatsapp, email, pass_code, consent_text, lead_ref_code)
    VALUES (k_slug, k_partner, 'Reh Anon Coded', '+573001234568', 'reh-b2@example.com', 'RH-BTWO', k_consent, 'KQ7M2Z');
    b2_state := 'SUCCEEDED -- a client chose its own lead_ref_code';
  EXCEPTION WHEN OTHERS THEN
    b2_state := SQLSTATE || ' ' || SQLERRM;
    b2_ok := SQLSTATE = '42501';
  END;
  RESET ROLE;
EXCEPTION WHEN OTHERS THEN
  RESET ROLE; b2_state := 'scaffolding failed: ' || SQLERRM; b2_ok := false;
END;

-- B3: POSITIVE. /api/pase's write: the service role with a valid code.
BEGIN
  SET LOCAL ROLE service_role;
  INSERT INTO public.pass_leads (slug, partner_id, name, whatsapp, email, pass_code, consent_text, lead_ref_code, attr_ref)
  VALUES (k_slug, k_partner, 'Reh Server', '+573001234569', 'reh-b3@example.com', 'RH-BTRE', k_consent, 'KQ7M2Z', k_code)
  RETURNING id INTO v_id;
  RESET ROLE;
  SELECT lead_ref_code INTO v_txt FROM public.pass_leads WHERE id = v_id;
  b3_state := 'service role wrote lead_ref_code=' || coalesce(v_txt, 'NULL') || ' (read back)';
  b3_ok := v_txt = 'KQ7M2Z';
EXCEPTION WHEN OTHERS THEN
  RESET ROLE; b3_state := 'REFUSED /api/pase''s write: ' || SQLSTATE || ' ' || SQLERRM; b3_ok := false;
END;

-- B4: the shape CHECK refuses a code with a 0 in it (the alphabet has none).
BEGIN
  SET LOCAL ROLE service_role;
  BEGIN
    INSERT INTO public.pass_leads (slug, partner_id, name, whatsapp, email, pass_code, consent_text, lead_ref_code)
    VALUES (k_slug, k_partner, 'Reh Bad Code', '+573001234570', 'reh-b4@example.com', 'RH-BFOR', k_consent, 'KQ7M20');
    b4_state := 'SUCCEEDED -- a code outside the alphabet was stored';
  EXCEPTION WHEN OTHERS THEN
    b4_state := SQLSTATE || ' ' || SQLERRM;
    b4_ok := SQLSTATE = '23514' AND SQLERRM LIKE '%pass_leads_lead_ref_code_shape%';
  END;
  RESET ROLE;
EXCEPTION WHEN OTHERS THEN
  RESET ROLE; b4_state := 'scaffolding failed: ' || SQLERRM; b4_ok := false;
END;

-- B5: a duplicate code is a 23505 on the new index: the collision /api/pase retries.
BEGIN
  SET LOCAL ROLE service_role;
  BEGIN
    INSERT INTO public.pass_leads (slug, partner_id, name, whatsapp, email, pass_code, consent_text, lead_ref_code)
    VALUES (k_slug, k_partner, 'Reh Dup Code', '+573001234571', 'reh-b5@example.com', 'RH-BFVE', k_consent, 'KQ7M2Z');
    b5_state := 'SUCCEEDED -- two leads hold the same lead_ref_code';
  EXCEPTION WHEN OTHERS THEN
    b5_state := SQLSTATE || ' ' || SQLERRM;
    b5_ok := SQLSTATE = '23505' AND SQLERRM LIKE '%pass_leads_lead_ref_code_key%';
  END;
  RESET ROLE;
EXCEPTION WHEN OTHERS THEN
  RESET ROLE; b5_state := 'scaffolding failed: ' || SQLERRM; b5_ok := false;
END;

-- ── PART C: referrals ─────────────────────────────────────────────────────

-- C1: POSITIVE. A user creates their own code row (getOrCreateReferralCode).
BEGIN
  PERFORM set_config('request.jwt.claims', json_build_object('sub', k_ref::text, 'role', 'authenticated')::text, true);
  SET LOCAL ROLE authenticated;
  BEGIN
    INSERT INTO public.referrals (referrer_id, referral_code, status) VALUES (k_ref, k_code, 'pending');
    c1_state := 'the referrer created their own code row, as /referral does'; c1_ok := true;
  EXCEPTION WHEN OTHERS THEN
    c1_state := 'REFUSED the /referral page''s write: ' || SQLSTATE || ' ' || SQLERRM;
  END;
  RESET ROLE; PERFORM set_config('request.jwt.claims', NULL, true);
EXCEPTION WHEN OTHERS THEN
  RESET ROLE; PERFORM set_config('request.jwt.claims', NULL, true);
  c1_state := 'scaffolding failed: ' || SQLERRM; c1_ok := false;
END;

-- C2: THE FORGERY CLOSED. The same user claims to have referred someone.
BEGIN
  PERFORM set_config('request.jwt.claims', json_build_object('sub', k_ref::text, 'role', 'authenticated')::text, true);
  SET LOCAL ROLE authenticated;
  BEGIN
    INSERT INTO public.referrals (referrer_id, referred_id, referral_code, status)
    VALUES (k_ref, k_new, k_code, 'signed_up');
    c2_state := 'SUCCEEDED -- a user forged a referral of another account';
  EXCEPTION WHEN OTHERS THEN
    c2_state := SQLSTATE || ' ' || SQLERRM;
    c2_ok := SQLSTATE = '42501';
  END;
  RESET ROLE; PERFORM set_config('request.jwt.claims', NULL, true);
EXCEPTION WHEN OTHERS THEN
  RESET ROLE; PERFORM set_config('request.jwt.claims', NULL, true);
  c2_state := 'scaffolding failed: ' || SQLERRM; c2_ok := false;
END;

-- C3: POSITIVE. The server's link (linkSignupReferral): look up the code row,
-- then insert the credit, both as the service role.
BEGIN
  SET LOCAL ROLE service_role;
  SELECT referrer_id INTO v_id FROM public.referrals
   WHERE referral_code = k_code AND referred_id IS NULL LIMIT 1;
  INSERT INTO public.referrals (referrer_id, referred_id, referral_code, status, converted_at)
  VALUES (v_id, k_new, k_code, 'signed_up', now());
  RESET ROLE;
  SELECT count(*) INTO v_n FROM public.referrals WHERE referrer_id = k_ref AND referred_id = k_new;
  c3_state := 'lookup found referrer ' || CASE WHEN v_id = k_ref THEN 'correctly' ELSE 'WRONG' END
    || '; ' || v_n || ' credit row written';
  c3_ok := v_id = k_ref AND v_n = 1;
EXCEPTION WHEN OTHERS THEN
  RESET ROLE; c3_state := 'REFUSED the server''s link: ' || SQLSTATE || ' ' || SQLERRM; c3_ok := false;
END;

-- C4: a second credit for the same person is refused by the one-credit index.
BEGIN
  SET LOCAL ROLE service_role;
  BEGIN
    INSERT INTO public.referrals (referrer_id, referred_id, referral_code, status)
    VALUES (k_ref, k_new, 'TRIBE-OTHER', 'signed_up');
    c4_state := 'SUCCEEDED -- one person credited twice';
  EXCEPTION WHEN OTHERS THEN
    c4_state := SQLSTATE || ' ' || SQLERRM;
    c4_ok := SQLSTATE = '23505' AND SQLERRM LIKE '%referrals_one_credit_per_referred%';
  END;
  RESET ROLE;
EXCEPTION WHEN OTHERS THEN
  RESET ROLE; c4_state := 'scaffolding failed: ' || SQLERRM; c4_ok := false;
END;

-- ── PART D: 215's guard, unmutated and against four mutations ─────────────

BEGIN
  EXECUTE v_guard;
  d0_state := 'guard passed on the migrated schema'; d0_ok := true;
EXCEPTION WHEN OTHERS THEN
  d0_state := 'guard REFUSED the real end state: ' || SQLERRM;
END;

BEGIN
  DROP POLICY "Lead referral code is server only" ON public.pass_leads;
  IF EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'pass_leads' AND policyname = 'Lead referral code is server only') THEN
    RAISE EXCEPTION 'MUTATION_DID_NOT_LAND';
  END IF;
  EXECUTE v_guard;
  RAISE EXCEPTION 'GUARD_DID_NOT_FIRE';
EXCEPTION WHEN OTHERS THEN
  d1_state := SQLERRM; d1_ok := SQLERRM LIKE '215 ABORTED: policy "Lead referral code is server only"%';
END;

BEGIN
  DROP INDEX public.referrals_one_credit_per_referred;
  CREATE INDEX referrals_one_credit_per_referred ON public.referrals (referred_id);
  IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'referrals_one_credit_per_referred'
              AND indexdef ILIKE 'CREATE UNIQUE INDEX%') THEN
    RAISE EXCEPTION 'MUTATION_DID_NOT_LAND';
  END IF;
  EXECUTE v_guard;
  RAISE EXCEPTION 'GUARD_DID_NOT_FIRE';
EXCEPTION WHEN OTHERS THEN
  d2_state := SQLERRM; d2_ok := SQLERRM LIKE '215 ABORTED: referrals_one_credit_per_referred is missing, not unique%';
END;

BEGIN
  DROP POLICY "Clients create only code rows" ON public.referrals;
  IF EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'referrals' AND policyname = 'Clients create only code rows') THEN
    RAISE EXCEPTION 'MUTATION_DID_NOT_LAND';
  END IF;
  EXECUTE v_guard;
  RAISE EXCEPTION 'GUARD_DID_NOT_FIRE';
EXCEPTION WHEN OTHERS THEN
  d3_state := SQLERRM; d3_ok := SQLERRM LIKE '215 ABORTED: policy "Clients create only code rows"%';
END;

-- D4: the same policy recreated PERMISSIVE, where it would be ORed away and
-- restrict nothing (CLAUDE.md: permissive policies OR together).
BEGIN
  DROP POLICY "Clients create only code rows" ON public.referrals;
  CREATE POLICY "Clients create only code rows" ON public.referrals FOR INSERT WITH CHECK (referred_id IS NULL);
  IF (SELECT permissive FROM pg_policies WHERE tablename = 'referrals' AND policyname = 'Clients create only code rows') <> 'PERMISSIVE' THEN
    RAISE EXCEPTION 'MUTATION_DID_NOT_LAND';
  END IF;
  EXECUTE v_guard;
  RAISE EXCEPTION 'GUARD_DID_NOT_FIRE';
EXCEPTION WHEN OTHERS THEN
  d4_state := SQLERRM; d4_ok := SQLERRM LIKE '215 ABORTED: policy "Clients create only code rows"%';
END;

-- ── PART E: the bug reverted ───────────────────────────────────────────────
-- Without 215's referrals policy, can a user forge a referral? YES is the
-- premise: the pre-existing policy admits it, and 215 is the only thing closing it.
BEGIN
  DROP POLICY "Clients create only code rows" ON public.referrals;
  PERFORM set_config('request.jwt.claims', json_build_object('sub', k_ref::text, 'role', 'authenticated')::text, true);
  SET LOCAL ROLE authenticated;
  BEGIN
    INSERT INTO public.referrals (referrer_id, referred_id, referral_code, status)
    VALUES (k_ref, k_ref, k_code, 'signed_up');
    e1_state := 'without 215''s policy, a user forged a referral row'; e1_ok := true;
  EXCEPTION WHEN OTHERS THEN
    e1_state := 'without 215''s policy the forgery was STILL refused: ' || SQLSTATE || ' ' || SQLERRM;
  END;
  RESET ROLE; PERFORM set_config('request.jwt.claims', NULL, true);
  RAISE EXCEPTION 'E1_ROLLBACK';
EXCEPTION WHEN OTHERS THEN
  RESET ROLE; PERFORM set_config('request.jwt.claims', NULL, true);
  IF SQLERRM <> 'E1_ROLLBACK' THEN e1_state := 'scaffolding failed: ' || SQLERRM; e1_ok := false; END IF;
END;

-- ── PART F: baseline ──────────────────────────────────────────────────────
SELECT count(*) INTO v_n FROM public.referrals
 WHERE referred_id IS NOT NULL AND referred_id NOT IN (k_ref, k_new);
f1_state := v_n || ' real referrals rows carry a referred_id (the one-credit index needed 0 duplicates)';
f1_ok := true;
f1_ok := NOT EXISTS (SELECT referred_id FROM public.referrals WHERE referred_id IS NOT NULL
                      GROUP BY referred_id HAVING count(*) > 1);

SELECT count(*) INTO v_n FROM public.pass_leads WHERE lead_ref_code IS NOT NULL AND slug <> k_slug;
f2_state := v_n || ' real pass leads carry a lead_ref_code (must be 0: the column is new)';
f2_ok := v_n = 0;

INSERT INTO reh_probe VALUES
  (1,  'A1 the column, two partial unique indexes, two restrictive policies', a1_state, a1_ok),
  (2,  'A2 SCAFFOLDING: two throwaway signups and a throwaway partner with a live pass', a2_state, a2_ok),
  (3,  'F3 IDENTITY: auth.uid() is NULL outside the arms', f3_state, f3_ok),
  (4,  'B1 POSITIVE: an anonymous claim with no code still works (the live form)', b1_state, b1_ok),
  (5,  'B2 an anonymous claim bringing its own lead_ref_code is refused', b2_state, b2_ok),
  (6,  'B3 POSITIVE: /api/pase''s service-role write with a code, read back', b3_state, b3_ok),
  (7,  'B4 a code outside the alphabet is refused by the shape CHECK', b4_state, b4_ok),
  (8,  'B5 a duplicate code is a 23505 on the new index (the retry path)', b5_state, b5_ok),
  (9,  'C1 POSITIVE: a user still creates their own code row (/referral)', c1_state, c1_ok),
  (10, 'C2 a user can no longer forge a referral of another account', c2_state, c2_ok),
  (11, 'C3 POSITIVE: the server''s lookup and link write the credit', c3_state, c3_ok),
  (12, 'C4 one credit per referred person', c4_state, c4_ok),
  (13, 'D0 POSITIVE: 215''s guard passes on the real end state', d0_state, d0_ok),
  (14, 'D1 guard fires when the pass_leads policy is missing', d1_state, d1_ok),
  (15, 'D2 guard fires when the one-credit index is not unique', d2_state, d2_ok),
  (16, 'D3 guard fires when the referrals policy is missing', d3_state, d3_ok),
  (17, 'D4 guard fires when the referrals policy is PERMISSIVE', d4_state, d4_ok),
  (18, 'E1 PREMISE: without 215, a user CAN forge a referral', e1_state, e1_ok),
  (19, 'F1 BASELINE: no referred person is already credited twice', f1_state, f1_ok),
  (20, 'F2 BASELINE: no real lead has a lead_ref_code yet', f2_state, f2_ok);

END $outer$;

-- The one result set for the transaction. Every row must read PASS. 20 of 20.
SELECT seq, CASE WHEN coalesce(passed, false) THEN 'PASS' ELSE 'FAIL' END AS result, check_name,
       coalesce(detail, '(probe row missing)') AS detail
FROM reh_probe ORDER BY seq;

ROLLBACK;

-- ══════════════════════════════════════════════════════════════════════════
-- PART G: nothing escaped. RUN AS ITS OWN STATEMENT, AFTER THE ROLLBACK.
-- Expected BEFORE apply: no lead_ref_code, neither index nor policy, no
-- rehearsal rows anywhere, 215 not recorded.
-- ══════════════════════════════════════════════════════════════════════════

SELECT t.seq, CASE WHEN t.passed THEN 'PASS' ELSE 'FAIL' END AS result, t.check_name, t.detail
FROM (VALUES
  (1, 'G1 pass_leads has no lead_ref_code column',
      (SELECT coalesce(string_agg(attname, ', '), '(none, as expected)') FROM pg_attribute
        WHERE attrelid = 'public.pass_leads'::regclass AND attname = 'lead_ref_code' AND NOT attisdropped),
      NOT EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid = 'public.pass_leads'::regclass
                   AND attname = 'lead_ref_code' AND NOT attisdropped)),
  (2, 'G2 neither new index nor new policy exists',
      (SELECT count(*) FROM pg_indexes WHERE indexname IN ('pass_leads_lead_ref_code_key', 'referrals_one_credit_per_referred'))::text
      || ' indexes, '
      || (SELECT count(*) FROM pg_policies WHERE policyname IN ('Lead referral code is server only', 'Clients create only code rows'))::text
      || ' policies',
      NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname IN ('pass_leads_lead_ref_code_key', 'referrals_one_credit_per_referred'))
      AND NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname IN ('Lead referral code is server only', 'Clients create only code rows'))),
  (3, 'G3 no rehearsal account, partner, lead or referral escaped',
      (SELECT count(*) FROM auth.users WHERE email LIKE 'reh-215-%')::text || ' auth, '
      || (SELECT count(*) FROM public.featured_partners WHERE slug LIKE 'reh215%')::text || ' partners, '
      || (SELECT count(*) FROM public.pass_leads WHERE slug LIKE 'reh215%')::text || ' leads, '
      || (SELECT count(*) FROM public.referrals WHERE referral_code IN ('TRIBE-RH215', 'TRIBE-OTHER'))::text || ' referrals',
      (SELECT count(*) FROM auth.users WHERE email LIKE 'reh-215-%') = 0
      AND (SELECT count(*) FROM public.featured_partners WHERE slug LIKE 'reh215%') = 0
      AND (SELECT count(*) FROM public.pass_leads WHERE slug LIKE 'reh215%') = 0
      AND (SELECT count(*) FROM public.referrals WHERE referral_code IN ('TRIBE-RH215', 'TRIBE-OTHER')) = 0),
  (4, 'G4 the three pre-existing referrals policies are untouched',
      (SELECT string_agg(policyname, ' | ' ORDER BY policyname) FROM pg_policies WHERE schemaname = 'public' AND tablename = 'referrals'),
      (SELECT count(*) FROM pg_policies WHERE schemaname = 'public' AND tablename = 'referrals') = 3),
  (5, 'G5 215 is NOT recorded as applied',
      (SELECT coalesce(string_agg(migration, ', '), '(not recorded, as expected)')
         FROM public.migrations_applied WHERE migration LIKE '215%'),
      (SELECT count(*) FROM public.migrations_applied WHERE migration LIKE '215%') = 0)
) AS t(seq, check_name, detail, passed)
ORDER BY t.seq;
