-- 214_t_grow1_signup_attribution_REHEARSAL.sql
--
-- GENERATED by supabase/recon/t-grow1c-build-rehearsal.LOCAL.py from
-- supabase/recon/214_REHEARSAL.template.sql. Edit the template, then rebuild;
-- the migration body and its guard are spliced in, never retyped.
--
-- Rehearsal for supabase/migrations/214_t_grow1_signup_attribution.sql. Run in
-- the Supabase SQL editor. Everything through the ROLLBACK is inside
-- BEGIN ... ROLLBACK; production is not modified. ONE result set for the
-- transaction, because the editor shows only the last statement's result.
--
-- Part A  the migration body, INCLUDING ITS DO GUARD, spliced verbatim. If the
--         guard raises, the script aborts with no result table: the loud
--         failure, and why it is first. A1/A2 re-assert the catalog and build
--         the scaffolding.
-- Part B  every writer, both directions (B11 is row 25). B1 and B4 are the POSITIVE arms and
--         they are the point: B1 is the route's exact write, and B4 is
--         upsertUserProfile's exact upsert, which runs on EVERY sign-in. A
--         guard that refused B4 would break sign-in for everyone.
-- Part D  the migration's own guard, run against five mutations, each one
--         asserting the mutation LANDED before reading the guard's answer, and
--         D0 running it unmutated to prove it passes on the real end state.
-- Part E  the bug reverted: drop the trigger and show an ordinary signed-in
--         user CAN then write their own attribution. That is the premise the
--         whole migration rests on, measured rather than read off a catalog.
-- Part F  premises and baseline, measured here.
-- Part G  nothing escaped -- DELIBERATELY OUTSIDE THE TRANSACTION.
--
-- ─────────────────────────────────────────────────────────────────────────────
-- THROWAWAY ACCOUNTS, NOT REAL ONES.
--
-- Three auth.users rows are inserted inside the transaction (reh-214-*@example.com).
-- handle_new_user creates their public.users rows exactly as a real signup
-- does, so the arms run against the production trigger path too. No real
-- account's row is written by any arm. The ADMIN arm (B6) borrows a real
-- admin's id as the JWT `sub` only, to be the actor; it writes to a throwaway
-- row, never to the admin's.
--
-- WHY ASSERT ON THE MESSAGE AND NOT ONLY 42501: RLS refusals are also 42501.
-- An arm that accepted any 42501 could not tell the trigger working from a
-- policy refusing for an unrelated reason, so the refusal arms match the
-- trigger's own text.
--
-- Scaffolding note: nothing running as anon or authenticated writes to the
-- probe table. Findings go into plpgsql variables and rows are written at the
-- end. Every probe read is coalesced so a missing row reads FAIL, not NULL.

BEGIN;

-- ══════════════════════════════════════════════════════════════════════════
-- PART A: the migration body, spliced verbatim from
--         supabase/migrations/214_t_grow1_signup_attribution.sql
--         (its BEGIN/COMMIT and its migrations_applied INSERT omitted)
-- ══════════════════════════════════════════════════════════════════════════

-- @@MIGRATION_BODY@@

-- ══════════════════════════════════════════════════════════════════════════
-- PARTS B to F
-- ══════════════════════════════════════════════════════════════════════════
CREATE TEMP TABLE reh_probe (seq integer, check_name text, detail text, passed boolean);

DO $outer$
DECLARE
  -- The migration's own DO guard, spliced verbatim, for Part D.
  v_guard text := $guard$@@GUARD_DO_BLOCK@@$guard$;

  k_new   uuid := gen_random_uuid();   -- a fresh signup
  k_old   uuid := gen_random_uuid();   -- an account aged to 30 days
  k_ins   uuid := gen_random_uuid();   -- unstamped row for the CHECK arms
  k_admin uuid;
  v_n integer; v_txt text; v_row record; v_id uuid;
  k_tag40  text := repeat('a', 40);
  k_path   text := '/' || repeat('p', 199);
  k_first  jsonb := jsonb_build_object('src', 'runclub', 'code', 'RUNCLUB-SAT0927', 'ref', NULL,
                      'utm_source', NULL, 'utm_medium', NULL, 'utm_campaign', 'hyrox-oct',
                      'utm_content', NULL, 'landing_path', '/', 'ts', 1791547200000);

  a1_state text := '(never ran)'; a1_ok boolean := false;
  a2_state text := '(never ran)'; a2_ok boolean := false;
  f5_state text := '(never ran)'; f5_ok boolean := false;
  b1_state text := '(never ran)'; b1_ok boolean := false;
  b2_state text := '(never ran)'; b2_ok boolean := false;
  b3_state text := '(never ran)'; b3_ok boolean := false;
  b4_state text := '(never ran)'; b4_ok boolean := false;
  b5_state text := '(never ran)'; b5_ok boolean := false;
  b6_state text := '(never ran)'; b6_ok boolean := false;
  b7_state text := '(never ran)'; b7_ok boolean := false;
  b8_state text := '(never ran)'; b8_ok boolean := false;
  b9_state text := '(never ran)'; b9_ok boolean := false;
  b10_state text := '(never ran)'; b10_ok boolean := false;
  b11_state text := '(never ran)'; b11_ok boolean := false;
  b11_with text; b11_without text;
  d0_state text := '(never ran)'; d0_ok boolean := false;
  d1_state text := '(never ran)'; d1_ok boolean := false;
  d2_state text := '(never ran)'; d2_ok boolean := false;
  d3_state text := '(never ran)'; d3_ok boolean := false;
  d4_state text := '(never ran)'; d4_ok boolean := false;
  d5_state text := '(never ran)'; d5_ok boolean := false;
  e1_state text := '(never ran)'; e1_ok boolean := false;
  f1_state text := '(never ran)'; f1_ok boolean := false;
  f2_state text := '(never ran)'; f2_ok boolean := false;
  f3_state text := '(never ran)'; f3_ok boolean := false;
  f4_state text := '(never ran)'; f4_ok boolean := false;
BEGIN

-- A1: the catalog, independently of the guard that already passed.
SELECT count(*) INTO v_n FROM pg_attribute
 WHERE attrelid = 'public.users'::regclass AND attnum > 0 AND NOT attisdropped AND attname LIKE 'signup\_%';
a1_state := v_n || ' signup_* columns, '
  || (SELECT count(*) FROM pg_constraint WHERE conrelid = 'public.users'::regclass
       AND conname LIKE 'users\_signup\_%' AND contype = 'c' AND convalidated) || ' validated CHECKs, trigger '
  || coalesce((SELECT CASE tgenabled WHEN 'O' THEN 'enabled' ELSE 'NOT enabled' END FROM pg_trigger
                WHERE tgrelid = 'public.users'::regclass AND tgname = 'users_signup_attribution_guard'), 'ABSENT');
a1_ok := v_n = 10 AND a1_state LIKE '%4 validated CHECKs, trigger enabled';

-- A2: scaffolding. Three throwaway signups through the real auth path.
BEGIN
  INSERT INTO auth.users (id, email, created_at, raw_user_meta_data)
  VALUES (k_new, 'reh-214-new@example.com', now(), '{"name":"Reh New"}'::jsonb),
         (k_old, 'reh-214-old@example.com', now(), '{"name":"Reh Old"}'::jsonb),
         (k_ins, 'reh-214-ins@example.com', now(), '{"name":"Reh Ins"}'::jsonb);
  UPDATE public.users SET created_at = now() - interval '30 days' WHERE id = k_old;
  SELECT id INTO k_admin FROM public.users WHERE is_admin IS TRUE ORDER BY created_at LIMIT 1;
  SELECT count(*) INTO v_n FROM public.users WHERE id IN (k_new, k_old, k_ins);
  a2_state := v_n || ' of 3 throwaway users rows created by handle_new_user; admin actor '
    || CASE WHEN k_admin IS NULL THEN 'NOT FOUND' ELSE 'resolved' END;
  a2_ok := v_n = 3 AND k_admin IS NOT NULL;
EXCEPTION WHEN OTHERS THEN
  a2_state := 'scaffolding failed: ' || SQLSTATE || ' ' || SQLERRM; a2_ok := false;
END;

-- F5: who is running this. CLAUDE.md: assert the role identity before any
-- arm whose meaning depends on it.
f5_state := 'current_user=' || current_user || ' session_user=' || session_user
  || ' auth.uid()=' || coalesce(auth.uid()::text, 'NULL');
f5_ok := auth.uid() IS NULL;

-- ── PART B ────────────────────────────────────────────────────────────────

-- B1: THE ROUTE'S WRITE, exactly: service role, no sub, the WHERE clause
-- recordSignupAttribution sends. 40 char tags and a 200 char path are the
-- largest values the sanitizers emit; refusing them would lose real signups.
BEGIN
  PERFORM set_config('request.jwt.claims', '{"role":"service_role"}', true);
  SET LOCAL ROLE service_role;
  BEGIN
    UPDATE public.users
       SET signup_src = 'ig', signup_code = 'IG-REEL-01', signup_ref = upper(k_tag40),
           signup_utm_source = k_tag40, signup_utm_medium = 'social', signup_utm_campaign = 'hyrox-oct',
           signup_utm_content = 'reel', signup_landing_path = k_path, signup_first_touch = k_first,
           signup_attributed_at = now()
     WHERE id = k_new AND signup_attributed_at IS NULL AND created_at >= now() - interval '7 days'
    RETURNING id INTO v_id;
    b1_state := 'wrote ' || CASE WHEN v_id IS NULL THEN '0 rows' ELSE '1 row' END;
  EXCEPTION WHEN OTHERS THEN
    b1_state := 'REFUSED the route''s own write: ' || SQLSTATE || ' ' || SQLERRM;
  END;
  RESET ROLE; PERFORM set_config('request.jwt.claims', NULL, true);
  SELECT * INTO v_row FROM public.users WHERE id = k_new;
  b1_ok := v_id IS NOT NULL AND v_row.signup_src = 'ig' AND v_row.signup_code = 'IG-REEL-01'
    AND v_row.signup_ref = upper(k_tag40) AND v_row.signup_utm_source = k_tag40
    AND v_row.signup_utm_medium = 'social' AND v_row.signup_utm_campaign = 'hyrox-oct'
    AND v_row.signup_utm_content = 'reel' AND v_row.signup_landing_path = k_path
    AND v_row.signup_first_touch = k_first AND v_row.signup_attributed_at IS NOT NULL;
  b1_state := b1_state || '; all ten read back ' || CASE WHEN b1_ok THEN 'as written' ELSE 'WRONG' END;
EXCEPTION WHEN OTHERS THEN
  RESET ROLE; PERFORM set_config('request.jwt.claims', NULL, true);
  b1_state := 'scaffolding failed: ' || SQLSTATE || ' ' || SQLERRM; b1_ok := false;
END;

-- B2: the same write against a 30-day-old account matches NOTHING, with no
-- error. That is the window rule living in the WHERE clause.
BEGIN
  PERFORM set_config('request.jwt.claims', '{"role":"service_role"}', true);
  SET LOCAL ROLE service_role;
  UPDATE public.users SET signup_src = 'ig', signup_attributed_at = now()
   WHERE id = k_old AND signup_attributed_at IS NULL AND created_at >= now() - interval '7 days';
  GET DIAGNOSTICS v_n = ROW_COUNT;
  RESET ROLE; PERFORM set_config('request.jwt.claims', NULL, true);
  b2_state := v_n || ' rows updated on the 30 day old account';
  b2_ok := v_n = 0 AND (SELECT signup_attributed_at IS NULL FROM public.users WHERE id = k_old);
EXCEPTION WHEN OTHERS THEN
  RESET ROLE; PERFORM set_config('request.jwt.claims', NULL, true);
  b2_state := SQLSTATE || ' ' || SQLERRM; b2_ok := false;
END;

-- B3: the OWNER, signed in, rewrites their own attribution. Refused by the
-- trigger (matched on its text), and the value is unchanged afterwards.
BEGIN
  PERFORM set_config('request.jwt.claims', json_build_object('sub', k_new::text, 'role', 'authenticated')::text, true);
  SET LOCAL ROLE authenticated;
  BEGIN
    UPDATE public.users SET signup_src = 'forged' WHERE id = k_new;
    GET DIAGNOSTICS v_n = ROW_COUNT;
    b3_state := 'SUCCEEDED (' || v_n || ' rows) -- a user rewrote their own attribution';
  EXCEPTION WHEN OTHERS THEN
    b3_state := SQLSTATE || ' ' || SQLERRM;
    b3_ok := SQLSTATE = '42501' AND SQLERRM LIKE '%recorded by the server only%';
  END;
  RESET ROLE; PERFORM set_config('request.jwt.claims', NULL, true);
  b3_ok := b3_ok AND (SELECT signup_src = 'ig' FROM public.users WHERE id = k_new);
EXCEPTION WHEN OTHERS THEN
  RESET ROLE; PERFORM set_config('request.jwt.claims', NULL, true);
  b3_state := 'scaffolding failed: ' || SQLSTATE || ' ' || SQLERRM; b3_ok := false;
END;

-- B4: POSITIVE, AND THE ONE THAT MATTERS MOST. upsertUserProfile's statement
-- shape, as the owner, on a row that HAS attribution: INSERT ... ON CONFLICT
-- (id) DO UPDATE. It fires the BEFORE INSERT branch and then the BEFORE UPDATE
-- branch. It runs on every sign-in in the app.
-- WITHOUT email in the SET list, deliberately: authenticated cannot SELECT
-- users.email (118; measured 2026-10-09), and reading EXCLUDED.email needs it,
-- so the with-email shape is refused by a GRANT whatever 214 does. B11 measures
-- that shape separately and asserts 214 does not change its outcome.
BEGIN
  PERFORM set_config('request.jwt.claims', json_build_object('sub', k_new::text, 'role', 'authenticated')::text, true);
  SET LOCAL ROLE authenticated;
  BEGIN
    INSERT INTO public.users (id, name, email) VALUES (k_new, 'Reh Renamed', 'reh-214-new@example.com')
    ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
    b4_state := 'profile upsert succeeded';
  EXCEPTION WHEN OTHERS THEN
    b4_state := 'REFUSED a profile upsert, so sign-in would break: ' || SQLSTATE || ' ' || SQLERRM;
  END;
  RESET ROLE; PERFORM set_config('request.jwt.claims', NULL, true);
  SELECT * INTO v_row FROM public.users WHERE id = k_new;
  b4_ok := b4_state = 'profile upsert succeeded' AND v_row.name = 'Reh Renamed'
    AND v_row.signup_src = 'ig' AND v_row.signup_first_touch = k_first;
  b4_state := b4_state || '; name=' || coalesce(v_row.name, 'NULL') || ', attribution intact='
    || (v_row.signup_src = 'ig' AND v_row.signup_first_touch = k_first)::text;
EXCEPTION WHEN OTHERS THEN
  RESET ROLE; PERFORM set_config('request.jwt.claims', NULL, true);
  b4_state := 'scaffolding failed: ' || SQLSTATE || ' ' || SQLERRM; b4_ok := false;
END;

-- B5: the INSERT branch. A client INSERT carrying attribution is refused by
-- the trigger. ON CONFLICT DO NOTHING because the row exists; BEFORE INSERT
-- triggers fire before the conflict is detected, so the branch is reached.
BEGIN
  PERFORM set_config('request.jwt.claims', json_build_object('sub', k_ins::text, 'role', 'authenticated')::text, true);
  SET LOCAL ROLE authenticated;
  BEGIN
    INSERT INTO public.users (id, name, email, signup_src, signup_attributed_at)
    VALUES (k_ins, 'Reh Ins', 'reh-214-ins@example.com', 'forged', now())
    ON CONFLICT (id) DO NOTHING;
    b5_state := 'SUCCEEDED -- a client INSERT carried attribution past the trigger';
  EXCEPTION WHEN OTHERS THEN
    b5_state := SQLSTATE || ' ' || SQLERRM;
    b5_ok := SQLSTATE = '42501' AND SQLERRM LIKE '%recorded by the server only%';
  END;
  RESET ROLE; PERFORM set_config('request.jwt.claims', NULL, true);
EXCEPTION WHEN OTHERS THEN
  RESET ROLE; PERFORM set_config('request.jwt.claims', NULL, true);
  b5_state := 'scaffolding failed: ' || SQLSTATE || ' ' || SQLERRM; b5_ok := false;
END;

-- B6: an ADMIN is refused too. The three older guards exempt admins; this one
-- deliberately does not (see 214's header). RLS admits the admin to the row via
-- "Admins can update any user", so the refusal must be the trigger's.
BEGIN
  PERFORM set_config('request.jwt.claims', json_build_object('sub', k_admin::text, 'role', 'authenticated')::text, true);
  SET LOCAL ROLE authenticated;
  BEGIN
    UPDATE public.users SET signup_code = 'ADMIN-EDIT' WHERE id = k_new;
    GET DIAGNOSTICS v_n = ROW_COUNT;
    b6_state := CASE WHEN v_n = 0 THEN 'UPDATE 0, no error: RLS filtered the row, so the admin path was NOT exercised'
                     ELSE 'SUCCEEDED -- an admin edited a signup attribution' END;
  EXCEPTION WHEN OTHERS THEN
    b6_state := SQLSTATE || ' ' || SQLERRM;
    b6_ok := SQLSTATE = '42501' AND SQLERRM LIKE '%recorded by the server only%';
  END;
  RESET ROLE; PERFORM set_config('request.jwt.claims', NULL, true);
EXCEPTION WHEN OTHERS THEN
  RESET ROLE; PERFORM set_config('request.jwt.claims', NULL, true);
  b6_state := 'scaffolding failed: ' || SQLSTATE || ' ' || SQLERRM; b6_ok := false;
END;

-- B7: write-once binds the SERVICE ROLE as well. A second write to a stamped
-- row is refused even from the only legitimate writer.
BEGIN
  PERFORM set_config('request.jwt.claims', '{"role":"service_role"}', true);
  SET LOCAL ROLE service_role;
  BEGIN
    UPDATE public.users SET signup_src = 'second', signup_attributed_at = now() WHERE id = k_new;
    b7_state := 'SUCCEEDED -- a stamped attribution was overwritten';
  EXCEPTION WHEN OTHERS THEN
    b7_state := SQLSTATE || ' ' || SQLERRM;
    b7_ok := SQLSTATE = '55000' AND SQLERRM LIKE '%written once%';
  END;
  RESET ROLE; PERFORM set_config('request.jwt.claims', NULL, true);
EXCEPTION WHEN OTHERS THEN
  RESET ROLE; PERFORM set_config('request.jwt.claims', NULL, true);
  b7_state := 'scaffolding failed: ' || SQLSTATE || ' ' || SQLERRM; b7_ok := false;
END;

-- B8: no attribution without a stamp (users_signup_attr_stamped).
BEGIN
  PERFORM set_config('request.jwt.claims', '{"role":"service_role"}', true);
  SET LOCAL ROLE service_role;
  BEGIN
    UPDATE public.users SET signup_src = 'ig' WHERE id = k_ins;
    b8_state := 'SUCCEEDED -- attribution with no signup_attributed_at';
  EXCEPTION WHEN OTHERS THEN
    b8_state := SQLSTATE || ' ' || SQLERRM;
    b8_ok := SQLSTATE = '23514' AND SQLERRM LIKE '%users_signup_attr_stamped%';
  END;
  RESET ROLE; PERFORM set_config('request.jwt.claims', NULL, true);
EXCEPTION WHEN OTHERS THEN
  RESET ROLE; PERFORM set_config('request.jwt.claims', NULL, true);
  b8_state := 'scaffolding failed: ' || SQLSTATE || ' ' || SQLERRM; b8_ok := false;
END;

-- B9: 41 characters is refused (B1 proved 40 is accepted).
BEGIN
  PERFORM set_config('request.jwt.claims', '{"role":"service_role"}', true);
  SET LOCAL ROLE service_role;
  BEGIN
    UPDATE public.users SET signup_src = repeat('a', 41), signup_attributed_at = now() WHERE id = k_ins;
    b9_state := 'SUCCEEDED -- a 41 character tag was stored';
  EXCEPTION WHEN OTHERS THEN
    b9_state := SQLSTATE || ' ' || SQLERRM;
    b9_ok := SQLSTATE = '23514' AND SQLERRM LIKE '%users_signup_attr_tag_bounds%';
  END;
  RESET ROLE; PERFORM set_config('request.jwt.claims', NULL, true);
EXCEPTION WHEN OTHERS THEN
  RESET ROLE; PERFORM set_config('request.jwt.claims', NULL, true);
  b9_state := 'scaffolding failed: ' || SQLSTATE || ' ' || SQLERRM; b9_ok := false;
END;

-- B10: a first_touch that is not an object is refused.
BEGIN
  PERFORM set_config('request.jwt.claims', '{"role":"service_role"}', true);
  SET LOCAL ROLE service_role;
  BEGIN
    UPDATE public.users SET signup_first_touch = '[1,2,3]'::jsonb, signup_attributed_at = now() WHERE id = k_ins;
    b10_state := 'SUCCEEDED -- an array was stored as first_touch';
  EXCEPTION WHEN OTHERS THEN
    b10_state := SQLSTATE || ' ' || SQLERRM;
    b10_ok := SQLSTATE = '23514' AND SQLERRM LIKE '%users_signup_first_touch_bounds%';
  END;
  RESET ROLE; PERFORM set_config('request.jwt.claims', NULL, true);
EXCEPTION WHEN OTHERS THEN
  RESET ROLE; PERFORM set_config('request.jwt.claims', NULL, true);
  b10_state := 'scaffolding failed: ' || SQLSTATE || ' ' || SQLERRM; b10_ok := false;
END;

-- B11: upsertUserProfile's FULL shape, email included, with and without 214's
-- trigger. PASS iff the outcome is identical: 214 must not change what this
-- statement does, whatever that is. The detail line is also a measurement of
-- what production does on every sign-in today, which is not 214's question
-- but is worth knowing (see B4 for why it may be refused).
BEGIN
  PERFORM set_config('request.jwt.claims', json_build_object('sub', k_old::text, 'role', 'authenticated')::text, true);
  SET LOCAL ROLE authenticated;
  BEGIN
    INSERT INTO public.users (id, name, email) VALUES (k_old, 'Reh Old', 'reh-214-old@example.com')
    ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, email = EXCLUDED.email;
    b11_with := 'succeeded';
  EXCEPTION WHEN OTHERS THEN
    b11_with := SQLSTATE || ' ' || SQLERRM;
  END;
  RESET ROLE; PERFORM set_config('request.jwt.claims', NULL, true);
  BEGIN
    DROP TRIGGER users_signup_attribution_guard ON public.users;
    PERFORM set_config('request.jwt.claims', json_build_object('sub', k_old::text, 'role', 'authenticated')::text, true);
    SET LOCAL ROLE authenticated;
    BEGIN
      INSERT INTO public.users (id, name, email) VALUES (k_old, 'Reh Old', 'reh-214-old@example.com')
      ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, email = EXCLUDED.email;
      b11_without := 'succeeded';
    EXCEPTION WHEN OTHERS THEN
      b11_without := SQLSTATE || ' ' || SQLERRM;
    END;
    RESET ROLE; PERFORM set_config('request.jwt.claims', NULL, true);
    RAISE EXCEPTION 'B11_ROLLBACK';
  EXCEPTION WHEN OTHERS THEN
    RESET ROLE; PERFORM set_config('request.jwt.claims', NULL, true);
    IF SQLERRM <> 'B11_ROLLBACK' THEN b11_without := 'scaffolding failed: ' || SQLERRM; END IF;
  END;
  b11_state := 'with 214: ' || coalesce(b11_with, '?') || ' | without: ' || coalesce(b11_without, '?');
  b11_ok := b11_with IS NOT NULL AND b11_with = b11_without;
EXCEPTION WHEN OTHERS THEN
  RESET ROLE; PERFORM set_config('request.jwt.claims', NULL, true);
  b11_state := 'scaffolding failed: ' || SQLSTATE || ' ' || SQLERRM; b11_ok := false;
END;

-- ── PART D: the migration's guard, unmutated and against five mutations ────
-- Each mutation asserts it LANDED before the guard's answer is read, and every
-- arm ends in an exception so the subtransaction rolls the mutation back.

-- D0: POSITIVE. The guard passes on the real end state.
BEGIN
  EXECUTE v_guard;
  d0_state := 'guard passed on the migrated schema'; d0_ok := true;
EXCEPTION WHEN OTHERS THEN
  d0_state := 'guard REFUSED the real end state: ' || SQLERRM; d0_ok := false;
END;

-- D1: a client SELECT grant on one column.
BEGIN
  GRANT SELECT (signup_ref) ON public.users TO authenticated;
  IF NOT has_column_privilege('authenticated', 'public.users', 'signup_ref', 'SELECT') THEN
    RAISE EXCEPTION 'MUTATION_DID_NOT_LAND';
  END IF;
  EXECUTE v_guard;
  RAISE EXCEPTION 'GUARD_DID_NOT_FIRE';
EXCEPTION WHEN OTHERS THEN
  d1_state := SQLERRM; d1_ok := SQLERRM LIKE '214 ABORTED: a client role can SELECT users.signup_ref%';
END;

-- D2: the trigger disabled.
BEGIN
  ALTER TABLE public.users DISABLE TRIGGER users_signup_attribution_guard;
  IF (SELECT tgenabled FROM pg_trigger WHERE tgrelid = 'public.users'::regclass
        AND tgname = 'users_signup_attribution_guard') <> 'D' THEN
    RAISE EXCEPTION 'MUTATION_DID_NOT_LAND';
  END IF;
  EXECUTE v_guard;
  RAISE EXCEPTION 'GUARD_DID_NOT_FIRE';
EXCEPTION WHEN OTHERS THEN
  d2_state := SQLERRM; d2_ok := SQLERRM LIKE '214 ABORTED: users_signup_attribution_guard is not an enabled%';
END;

-- D3: the stamp CHECK dropped.
BEGIN
  ALTER TABLE public.users DROP CONSTRAINT users_signup_attr_stamped;
  IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.users'::regclass
              AND conname = 'users_signup_attr_stamped') THEN
    RAISE EXCEPTION 'MUTATION_DID_NOT_LAND';
  END IF;
  EXECUTE v_guard;
  RAISE EXCEPTION 'GUARD_DID_NOT_FIRE';
EXCEPTION WHEN OTHERS THEN
  d3_state := SQLERRM; d3_ok := SQLERRM LIKE '214 ABORTED: CHECK users_signup_attr_stamped is missing%';
END;

-- D4: 213's comment put back, VERBATIM (spliced from 213's file by the
-- builder). Reverting the actual bug, not a lookalike: 213's text contains
-- "v1.1", and a guard checking for "v1.1" passed with it in place.
BEGIN
  @@COMMENT_213@@
  IF position('migration 214' IN obj_description('public.attribution_events'::regclass, 'pg_class')) > 0 THEN
    RAISE EXCEPTION 'MUTATION_DID_NOT_LAND';
  END IF;
  EXECUTE v_guard;
  RAISE EXCEPTION 'GUARD_DID_NOT_FIRE';
EXCEPTION WHEN OTHERS THEN
  d4_state := SQLERRM; d4_ok := SQLERRM LIKE '214 ABORTED: the attribution_events comment was not replaced%';
END;

-- D5: the trigger recreated as BEFORE UPDATE only, so a client INSERT escapes.
BEGIN
  DROP TRIGGER users_signup_attribution_guard ON public.users;
  CREATE TRIGGER users_signup_attribution_guard BEFORE UPDATE ON public.users
    FOR EACH ROW EXECUTE FUNCTION public.guard_signup_attribution();
  IF (SELECT tgtype & 4 FROM pg_trigger WHERE tgrelid = 'public.users'::regclass
        AND tgname = 'users_signup_attribution_guard') <> 0 THEN
    RAISE EXCEPTION 'MUTATION_DID_NOT_LAND';
  END IF;
  EXECUTE v_guard;
  RAISE EXCEPTION 'GUARD_DID_NOT_FIRE';
EXCEPTION WHEN OTHERS THEN
  d5_state := SQLERRM; d5_ok := SQLERRM LIKE '214 ABORTED: users_signup_attribution_guard is not an enabled%';
END;

-- ── PART E: the bug reverted ───────────────────────────────────────────────
-- Without the trigger, can an ordinary signed-in user write their own
-- attribution? If YES, the trigger is the only control and the migration's
-- premise holds. If NO, something else already blocks it and the header is
-- wrong about why the trigger exists.
BEGIN
  DROP TRIGGER users_signup_attribution_guard ON public.users;
  PERFORM set_config('request.jwt.claims', json_build_object('sub', k_ins::text, 'role', 'authenticated')::text, true);
  SET LOCAL ROLE authenticated;
  BEGIN
    UPDATE public.users SET signup_src = 'forged', signup_attributed_at = now() WHERE id = k_ins;
    GET DIAGNOSTICS v_n = ROW_COUNT;
    e1_state := 'without the trigger, the owner wrote ' || v_n || ' row(s) of their own attribution';
    e1_ok := v_n = 1;
  EXCEPTION WHEN OTHERS THEN
    e1_state := 'without the trigger the write was STILL refused: ' || SQLSTATE || ' ' || SQLERRM;
  END;
  RESET ROLE; PERFORM set_config('request.jwt.claims', NULL, true);
  RAISE EXCEPTION 'E1_ROLLBACK';
EXCEPTION WHEN OTHERS THEN
  RESET ROLE; PERFORM set_config('request.jwt.claims', NULL, true);
  IF SQLERRM <> 'E1_ROLLBACK' THEN e1_state := 'scaffolding failed: ' || SQLERRM; e1_ok := false; END IF;
END;

-- ── PART F: premises and baseline ─────────────────────────────────────────
f1_state := 'has_table_privilege(authenticated, users, UPDATE) = '
  || has_table_privilege('authenticated', 'public.users', 'UPDATE')::text;
f1_ok := has_table_privilege('authenticated', 'public.users', 'UPDATE');

f2_state := 'has_table_privilege(authenticated, users, INSERT) = '
  || has_table_privilege('authenticated', 'public.users', 'INSERT')::text;
f2_ok := has_table_privilege('authenticated', 'public.users', 'INSERT');

BEGIN
  PERFORM set_config('request.jwt.claims', '{"role":"service_role"}', true);
  SET LOCAL ROLE service_role;
  v_txt := coalesce(auth.uid()::text, 'NULL');
  RESET ROLE; PERFORM set_config('request.jwt.claims', NULL, true);
  f3_state := 'auth.uid() under the service role''s claims = ' || v_txt;
  f3_ok := v_txt = 'NULL';
EXCEPTION WHEN OTHERS THEN
  RESET ROLE; PERFORM set_config('request.jwt.claims', NULL, true);
  f3_state := SQLSTATE || ' ' || SQLERRM; f3_ok := false;
END;

DECLARE
  f4_real integer; f4_window integer; f4_attr integer;
BEGIN
  SELECT count(*),
         count(*) FILTER (WHERE created_at >= now() - interval '7 days'),
         count(*) FILTER (WHERE signup_attributed_at IS NOT NULL)
    INTO f4_real, f4_window, f4_attr
    FROM public.users WHERE id NOT IN (k_new, k_old, k_ins);
  f4_state := f4_real || ' real accounts, ' || f4_window || ' inside the 7 day window today, '
    || f4_attr || ' with attribution (must be 0)';
  f4_ok := f4_attr = 0;
END;

INSERT INTO reh_probe VALUES
  (1,  'A1 ten columns, four validated CHECKs, the trigger enabled', a1_state, a1_ok),
  (2,  'A2 SCAFFOLDING: three throwaway signups via handle_new_user, an admin actor', a2_state, a2_ok),
  (3,  'F5 IDENTITY: who runs this, and auth.uid() is NULL outside the arms', f5_state, f5_ok),
  (4,  'B1 POSITIVE: the route''s exact write, max-length values, all ten read back', b1_state, b1_ok),
  (5,  'B2 the route''s write matches nothing on a 30 day old account', b2_state, b2_ok),
  (6,  'B3 the owner cannot rewrite their own attribution (trigger, by message)', b3_state, b3_ok),
  (7,  'B4 POSITIVE: upsertUserProfile''s upsert still works on every sign-in', b4_state, b4_ok),
  (8,  'B5 a client INSERT carrying attribution is refused (INSERT branch)', b5_state, b5_ok),
  (9,  'B6 an ADMIN cannot edit attribution either', b6_state, b6_ok),
  (10, 'B7 write-once binds the service role: a second write is refused', b7_state, b7_ok),
  (11, 'B8 no attribution without signup_attributed_at', b8_state, b8_ok),
  (12, 'B9 a 41 character tag is refused', b9_state, b9_ok),
  (13, 'B10 a non-object first_touch is refused', b10_state, b10_ok),
  (14, 'D0 POSITIVE: the migration''s guard passes on the real end state', d0_state, d0_ok),
  (15, 'D1 guard fires on a client SELECT grant', d1_state, d1_ok),
  (16, 'D2 guard fires on a disabled trigger', d2_state, d2_ok),
  (17, 'D3 guard fires on a dropped stamp CHECK', d3_state, d3_ok),
  (18, 'D4 guard fires on 213''s comment restored', d4_state, d4_ok),
  (19, 'D5 guard fires on an UPDATE-only trigger', d5_state, d5_ok),
  (20, 'E1 PREMISE: without the trigger, the owner CAN write it', e1_state, e1_ok),
  (21, 'F1 PREMISE: authenticated holds table-level UPDATE on users', f1_state, f1_ok),
  (22, 'F2 PREMISE: authenticated holds INSERT on users', f2_state, f2_ok),
  (23, 'F3 PREMISE: the service role''s claims give auth.uid() = NULL', f3_state, f3_ok),
  (24, 'F4 BASELINE: real accounts, how many are inside the window, none attributed', f4_state, f4_ok),
  (25, 'B11 214 does not change what the full profile upsert (with email) does', b11_state, b11_ok);

END $outer$;

-- The one result set for the transaction. Every row must read PASS. 25 of 25.
SELECT seq, CASE WHEN coalesce(passed, false) THEN 'PASS' ELSE 'FAIL' END AS result, check_name,
       coalesce(detail, '(probe row missing)') AS detail
FROM reh_probe ORDER BY seq;

ROLLBACK;

-- ══════════════════════════════════════════════════════════════════════════
-- PART G: nothing escaped.
--
-- RUN THIS AS ITS OWN STATEMENT, AFTER THE ROLLBACK ABOVE HAS ENDED. A check
-- inside the transaction would read a database where the migration IS applied
-- and could not observe whether it escaped.
--
-- Expected BEFORE apply: no signup_* columns, no guard function or trigger,
-- 213's comment still in place, no reh-214 account, 214 not recorded.
-- ══════════════════════════════════════════════════════════════════════════

SELECT t.seq, CASE WHEN t.passed THEN 'PASS' ELSE 'FAIL' END AS result, t.check_name, t.detail
FROM (VALUES
  (1, 'G1 no signup_* column is on the live users table',
      (SELECT coalesce(string_agg(attname, ', ' ORDER BY attname), '(none, as expected)') FROM pg_attribute
        WHERE attrelid = 'public.users'::regclass AND attnum > 0 AND NOT attisdropped AND attname LIKE 'signup\_%'),
      (SELECT count(*) FROM pg_attribute
        WHERE attrelid = 'public.users'::regclass AND attnum > 0 AND NOT attisdropped AND attname LIKE 'signup\_%') = 0),
  (2, 'G2 no guard function and no guard trigger',
      coalesce(to_regprocedure('public.guard_signup_attribution()')::text, '(no function)') || ', '
      || (SELECT count(*) FROM pg_trigger WHERE tgrelid = 'public.users'::regclass
            AND tgname = 'users_signup_attribution_guard')::text || ' triggers',
      to_regprocedure('public.guard_signup_attribution()') IS NULL
      AND NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgrelid = 'public.users'::regclass
                        AND tgname = 'users_signup_attribution_guard')),
  (3, 'G3 attribution_events still carries 213''s comment',
      left(obj_description('public.attribution_events'::regclass, 'pg_class'), 60) || '...',
      position('migration 214' IN coalesce(obj_description('public.attribution_events'::regclass, 'pg_class'), '')) = 0),
  (4, 'G4 no rehearsal account escaped, in auth.users or public.users',
      (SELECT count(*) FROM auth.users WHERE email LIKE 'reh-214-%')::text || ' auth, '
      || (SELECT count(*) FROM public.users WHERE email LIKE 'reh-214-%')::text || ' public',
      (SELECT count(*) FROM auth.users WHERE email LIKE 'reh-214-%') = 0
      AND (SELECT count(*) FROM public.users WHERE email LIKE 'reh-214-%') = 0),
  (5, 'G5 214 is NOT recorded as applied',
      (SELECT coalesce(string_agg(migration, ', '), '(not recorded, as expected)')
         FROM public.migrations_applied WHERE migration LIKE '214%'),
      (SELECT count(*) FROM public.migrations_applied WHERE migration LIKE '214%') = 0)
) AS t(seq, check_name, detail, passed)
ORDER BY t.seq;
