/**
 * Syncs the applied-migration MIRROR from one place to both of its consumers.
 *
 *   npx tsx scripts/syncMigrationsApplied.ts 187_athlete_setup
 *   npx tsx scripts/syncMigrationsApplied.ts            # regenerate SQL from the JSON
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * WHY THIS EXISTS
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * public.migrations_applied (migration 184) is the source of truth. Two things
 * that cannot read it need to know what it contains:
 *
 *   - supabase/migrations_applied.json, read by migrationAppliedBeforeCode
 *     .test.ts, which runs with no database.
 *   - the mirror list embedded TWICE in verify-migration-state.sql, which is
 *     what lets the database assert the JSON matches the table.
 *
 * Those were three hand-kept copies of the same list, and the JSON's own
 * _comment told the next person to regenerate them with THIS script -- which
 * did not exist. A pointer to something you cannot find is a finding about the
 * thing pointing: the instruction had never been executable, so the only way
 * to add a migration was to edit three lists by hand and hope.
 *
 * Adding a migration is now one command, and migrationsAppliedMirror.test.ts
 * fails if the SQL copies drift from the JSON.
 *
 * THIS SCRIPT DOES NOT APPLY ANYTHING AND CANNOT CHECK THAT ANYTHING WAS
 * APPLIED. Running it records a claim. The claim is checked by the database,
 * in verify-migration-state.sql's GUARD_184 probe, in both directions -- a
 * mirror naming a migration the table has not recorded fails there, which is
 * the dishonest way to make the merge guard green.
 */
import { readFileSync, writeFileSync } from 'fs';

const JSON_PATH = 'supabase/migrations_applied.json';
const SQL_PATH = 'supabase/verify-migration-state.sql';
const BEGIN = '    -- <<<MIRROR_LIST>>> generated by scripts/syncMigrationsApplied.ts -- do not hand-edit\n';
const END = '    -- <<<END_MIRROR_LIST>>>\n';

interface Mirror {
  _comment: string;
  _recordStartsAt: number;
  _recordStartsAtWhy: string;
  applied: string[];
}

const mirror = JSON.parse(readFileSync(JSON_PATH, 'utf8')) as Mirror;
const add = process.argv[2];

if (add) {
  if (!/^\d{3}_[a-z0-9_]+$/.test(add)) {
    throw new Error(`Pass a migration basename with no extension, e.g. 187_athlete_setup. Got: ${add}`);
  }
  if (Number(add.slice(0, 3)) < mirror._recordStartsAt) {
    throw new Error(`${add} is below the record floor (${mirror._recordStartsAt}) and is presumed applied already.`);
  }
  if (!mirror.applied.includes(add)) {
    mirror.applied.push(add);
    // Numeric, not lexicographic: '9_x' before '10_x' matters once the series
    // passes 999, and sorting a list of strings is how that goes wrong quietly.
    mirror.applied.sort((a, b) => Number(a.slice(0, 3)) - Number(b.slice(0, 3)) || a.localeCompare(b));
    writeFileSync(JSON_PATH, JSON.stringify(mirror, null, 2) + '\n');
    console.log(`Added ${add} to ${JSON_PATH}`);
  } else {
    console.log(`${add} was already in ${JSON_PATH}`);
  }
}

export const renderMirrorList = (applied: string[]): string =>
  applied.map((m, i) => `    ('${m}')${i === applied.length - 1 ? '' : ','}\n`).join('');

const sql = readFileSync(SQL_PATH, 'utf8');
const body = renderMirrorList(mirror.applied);
const blocks = sql.split(BEGIN).length - 1;
if (blocks !== 2) {
  throw new Error(`Expected 2 mirror-list blocks in ${SQL_PATH}, found ${blocks}. Markers missing or duplicated.`);
}
// Replace only BETWEEN the markers, so nothing else in the probe can be
// rewritten by a greedy match.
const next = sql.replace(new RegExp(`${BEGIN}[\\s\\S]*?${END}`, 'g'), BEGIN + body + END);
if (next === sql) {
  console.log(`${SQL_PATH} already matches the JSON mirror`);
} else {
  writeFileSync(SQL_PATH, next);
  console.log(`Rewrote both mirror lists in ${SQL_PATH} (${mirror.applied.length} migrations)`);
}
