-- Migration 020: Add more hiking routes for Medellín area
-- Only 1 hiking route existed (Parque Arví). Adding 7 more for variety across difficulties.

INSERT INTO popular_routes (name, sport_type, distance_km, elevation_gain_m, difficulty, start_lat, start_lng, description_en, description_es) VALUES
('Cerro El Volador Summit Trail', 'hiking', 3.5, 200, 'moderate', 6.2630, -75.5920, 'Hike to the summit of Cerro El Volador for 360° views of the city. Pre-Colombian archaeological site at the top.', 'Senderismo a la cima del Cerro El Volador con vistas 360° de la ciudad. Sitio arqueológico precolombino en la cima.'),
('Cerro Pan de Azúcar', 'hiking', 6.0, 350, 'moderate', 6.2810, -75.5750, 'Forested trail to Pan de Azúcar peak in northern Medellín. Quiet paths with bird-watching opportunities.', 'Sendero boscoso al pico Pan de Azúcar en el norte de Medellín. Caminos tranquilos con avistamiento de aves.'),
('Cerro Quitasol', 'hiking', 8.0, 600, 'hard', 6.3200, -75.5500, 'Challenging hike to the iconic Quitasol peak above Bello. Stunning panoramic views of the Aburrá Valley.', 'Caminata desafiante al icónico pico Quitasol sobre Bello. Vistas panorámicas impresionantes del Valle de Aburrá.'),
('La Romera Ecological Park', 'hiking', 10.0, 500, 'hard', 6.1500, -75.6000, 'Ecological reserve trails in Sabaneta with native forest, waterfalls, and wildlife. Full-day adventure.', 'Senderos de reserva ecológica en Sabaneta con bosque nativo, cascadas y fauna. Aventura de día completo.'),
('Salto del Ángel Waterfall Trail', 'hiking', 5.0, 280, 'moderate', 6.2900, -75.4950, 'Trail through cloud forest to the Angel Falls waterfall near Santa Elena. Refreshing swim at the end.', 'Sendero por bosque de niebla hasta la cascada Salto del Ángel cerca de Santa Elena. Baño refrescante al final.'),
('Santa Elena Flower Farms Walk', 'hiking', 4.0, 150, 'easy', 6.2200, -75.5000, 'Gentle walk through the flower farms of Santa Elena. Home of the famous silleteros. Family-friendly.', 'Caminata suave por las fincas de flores de Santa Elena. Hogar de los famosos silleteros. Apto para familias.'),
('Piedra del Peñol Trail', 'hiking', 2.5, 200, 'moderate', 6.2210, -75.1790, 'The iconic 740-step climb up La Piedra del Peñol. Breathtaking views of the Guatapé reservoir.', 'La icónica subida de 740 escalones de La Piedra del Peñol. Vistas impresionantes del embalse de Guatapé.'),
('Jardín Botánico Nature Walk', 'hiking', 2.0, 20, 'easy', 6.2710, -75.5640, 'Easy nature walk through the Botanical Garden. Shaded paths, butterfly garden, and orchid collection.', 'Caminata fácil por el Jardín Botánico. Senderos sombreados, jardín de mariposas y colección de orquídeas.');

-- Additional cycling routes for variety across the Medellín metro area
INSERT INTO popular_routes (name, sport_type, distance_km, elevation_gain_m, difficulty, start_lat, start_lng, description_en, description_es) VALUES
('Envigado to Sabaneta Bike Path', 'cycling', 8.0, 60, 'easy', 6.1710, -75.5830, 'Flat bike path connecting Envigado and Sabaneta along the river corridor. Great for beginners and casual rides.', 'Ciclovía plana conectando Envigado y Sabaneta a lo largo del corredor del río. Ideal para principiantes y paseos casuales.'),
('Itagüí Industrial Zone Loop', 'cycling', 12.0, 150, 'moderate', 6.1850, -75.6120, 'Loop ride through Itagüí passing industrial landmarks and local parks. Mix of bike lanes and quiet streets.', 'Recorrido en circuito por Itagüí pasando por hitos industriales y parques locales. Mezcla de ciclovías y calles tranquilas.'),
('Belén to San Cristóbal Road', 'cycling', 14.0, 320, 'moderate', 6.2340, -75.6100, 'Climb from Belén neighborhood westward to the village of San Cristóbal. Rewarding views of the valley on the way up.', 'Subida desde el barrio Belén hacia el corregimiento de San Cristóbal. Vistas gratificantes del valle durante el ascenso.'),
('Airport Greenway (Ciclorruta Aeropuerto)', 'cycling', 6.0, 30, 'easy', 6.1640, -75.6280, 'Flat dedicated cycling greenway near the Olaya Herrera airport. Smooth pavement, safe and family-friendly.', 'Ciclovía dedicada y plana cerca del aeropuerto Olaya Herrera. Pavimento liso, seguro y apto para familias.'),
('Robledo to Santa Elena Climb', 'cycling', 22.0, 1100, 'hard', 6.2780, -75.5750, 'Epic climb from Robledo through winding mountain roads up to Santa Elena. A classic challenge for strong cyclists.', 'Épica subida desde Robledo por carreteras sinuosas de montaña hasta Santa Elena. Un clásico desafío para ciclistas fuertes.');
