-- 215_t_grow2_referral_loop.sql
--
-- T-GROW2: the referral loop. EXTENDS the existing referrals system (014, 089)
-- rather than building a second one, per the T-GROW0 recon.
--
-- Covered by Politica de tratamiento de datos v1.1 (live 2026-10-09), section
-- 4: "when you join through someone's invitation link, we record that
-- connection so we can credit the person who invited you."
--
-- ─────────────────────────────────────────────────────────────────────────────
-- WHAT WAS MEASURED ON PRODUCTION BEFORE WRITING THIS (2026-10-09, SELECT only)
--
--   referrals: 7 rows, ALL `pending`, ALL with referred_id NULL. Zero
--   conversions, ever. The reason is in the policies, not the product:
--     * the only INSERT policy is WITH CHECK (auth.uid() = referrer_id), and
--       applyReferralCode() runs as the NEW user's browser client inserting a
--       row whose referrer_id is SOMEONE ELSE -- refused, every time;
--     * it never got that far: lookupReferralCode() reads the referrer's row
--       first, and the only SELECT policies are own-rows-only, so the new user
--       could not see it and the code read as "invalid".
--   So the client-side write path has never worked. T-GROW2 moves the write to
--   the server (/api/attr/signup, service role), and this file stops a client
--   from forging the other half.
--
--   THE FORGERY THAT WAS OPEN: the same INSERT policy admits any row where
--   referrer_id is the caller, with referred_id set to ANYONE. A user could
--   claim to have referred every account in the app. Section 3 below makes the
--   client path code-rows-only (referred_id IS NULL).
--
--   pass_leads: 5 policies, 2 RESTRICTIVE ("Attribution columns are server
--   only", 211; "Program columns are server only", 208). This adds a third.
--   anon and authenticated both hold table-level INSERT (173).
--
-- ─────────────────────────────────────────────────────────────────────────────
-- WHAT IT ADDS
--
-- 1. pass_leads.lead_ref_code: the 6 character code a pass lead shares (spec
--    T-GROW2 A: "6 chars, no 0/O/1/I"). NOT the pass_code. The pass_code is the
--    handle a person quotes at the gym's door; putting it in a public share
--    link would make every friend who receives the link able to quote it.
--    Server-generated by /api/pase, unique, and refused from any client insert.
--    Named lead_ref_code and not ref_code (taken by program_athletes) or
--    referral_code (users and referrals both have one, and
--    migrationAppliedBeforeCode matches column names as substrings).
-- 2. referrals_one_credit_per_referred: a person is referred ONCE. Partial, so
--    the code rows (referred_id NULL) are untouched. Measured: 0 rows have
--    referred_id, so this cannot fail on existing data.
-- 3. "Clients create only code rows": RESTRICTIVE, so it ANDs with the existing
--    permissive policy instead of being ORed away (CLAUDE.md on permissive
--    policies). getOrCreateReferralCode (the /referral page) inserts exactly a
--    code row and is unaffected.
--
-- What it deliberately does NOT touch: users.referred_by / users.referral_code
-- (both unused: 0 rows set), the status column and its progression (no UPDATE
-- policy exists, so referrals-progression.ts has never been able to write
-- either -- a separate finding, not this ticket's), and the existing policies,
-- which are left exactly as they are and asserted below.
--
-- RE-RUNNABLE: IF NOT EXISTS / DROP ... IF EXISTS throughout. One paste is one
-- transaction.

BEGIN;

-- ── 1. pass_leads.lead_ref_code ─────────────────────────────────────────────
ALTER TABLE public.pass_leads ADD COLUMN IF NOT EXISTS lead_ref_code text;

COMMENT ON COLUMN public.pass_leads.lead_ref_code IS
  'T-GROW2. The code this lead shares in "Trae a un amigo" links (?ref=CODE). '
  'Six characters, no 0/O/1/I. Generated server side by /api/pase; refused from '
  'any client insert. A friend who claims through the link carries it as attr_ref. '
  'Deliberately NOT the pass_code, which is the door handle and stays private.';

ALTER TABLE public.pass_leads DROP CONSTRAINT IF EXISTS pass_leads_lead_ref_code_shape;
ALTER TABLE public.pass_leads
  ADD CONSTRAINT pass_leads_lead_ref_code_shape
  CHECK (lead_ref_code IS NULL OR lead_ref_code ~ '^[A-HJ-NP-Z2-9]{6}$');

CREATE UNIQUE INDEX IF NOT EXISTS pass_leads_lead_ref_code_key
  ON public.pass_leads (lead_ref_code) WHERE lead_ref_code IS NOT NULL;

DROP POLICY IF EXISTS "Lead referral code is server only" ON public.pass_leads;
CREATE POLICY "Lead referral code is server only" ON public.pass_leads
  AS RESTRICTIVE
  FOR INSERT
  WITH CHECK (lead_ref_code IS NULL);

-- ── 2. One credit per referred person ───────────────────────────────────────
CREATE UNIQUE INDEX IF NOT EXISTS referrals_one_credit_per_referred
  ON public.referrals (referred_id) WHERE referred_id IS NOT NULL;

-- ── 3. Clients create only code rows ────────────────────────────────────────
DROP POLICY IF EXISTS "Clients create only code rows" ON public.referrals;
CREATE POLICY "Clients create only code rows" ON public.referrals
  AS RESTRICTIVE
  FOR INSERT
  WITH CHECK (referred_id IS NULL);

-- ── 4. Assert the end state ─────────────────────────────────────────────────
DO $$
DECLARE
  v_row record;
  v_name text;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid = 'public.pass_leads'::regclass
                  AND attname = 'lead_ref_code' AND NOT attisdropped AND atttypid = 'text'::regtype) THEN
    RAISE EXCEPTION '215 ABORTED: pass_leads.lead_ref_code is missing or is not text.';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.pass_leads'::regclass
                  AND conname = 'pass_leads_lead_ref_code_shape' AND contype = 'c' AND convalidated) THEN
    RAISE EXCEPTION '215 ABORTED: CHECK pass_leads_lead_ref_code_shape is missing or not validated.';
  END IF;

  -- Both indexes UNIQUE and PARTIAL. A non-partial index on referred_id would
  -- treat the code rows' NULLs as distinct and pass today, then mean something
  -- else if anyone ever made the column NOT NULL; asserting the predicate says
  -- what this index is for.
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND tablename = 'pass_leads'
                  AND indexname = 'pass_leads_lead_ref_code_key'
                  AND indexdef ILIKE 'CREATE UNIQUE INDEX%' AND indexdef ILIKE '%WHERE%lead_ref_code IS NOT NULL%') THEN
    RAISE EXCEPTION '215 ABORTED: pass_leads_lead_ref_code_key is missing, not unique, or not partial.';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND tablename = 'referrals'
                  AND indexname = 'referrals_one_credit_per_referred'
                  AND indexdef ILIKE 'CREATE UNIQUE INDEX%' AND indexdef ILIKE '%WHERE%referred_id IS NOT NULL%') THEN
    RAISE EXCEPTION '215 ABORTED: referrals_one_credit_per_referred is missing, not unique, or not partial.';
  END IF;

  -- The two new policies: RESTRICTIVE, FOR INSERT, every role, the right clause.
  FOR v_row IN
    SELECT * FROM (VALUES
      ('pass_leads', 'Lead referral code is server only', 'lead_ref_code IS NULL'),
      ('referrals',  'Clients create only code rows',     'referred_id IS NULL')
    ) AS t(tbl, pol, clause)
  LOOP
    IF NOT EXISTS (SELECT 1 FROM pg_policies p
                    WHERE p.schemaname = 'public' AND p.tablename = v_row.tbl AND p.policyname = v_row.pol
                      AND p.permissive = 'RESTRICTIVE' AND p.cmd = 'INSERT' AND p.roles::text = '{public}'
                      AND position(v_row.clause IN p.with_check) > 0) THEN
      RAISE EXCEPTION '215 ABORTED: policy "%" on % is missing, not RESTRICTIVE FOR INSERT for all roles, or lacks "%".',
        v_row.pol, v_row.tbl, v_row.clause;
    END IF;
  END LOOP;

  -- Nothing else was touched. Named, not counted: a count is satisfied by one
  -- policy being replaced by another.
  FOREACH v_name IN ARRAY ARRAY['Anyone can claim a pass', 'Admins manage pass leads', 'Partner reads own leads',
                                'Program columns are server only', 'Attribution columns are server only'] LOOP
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'pass_leads'
                    AND policyname = v_name) THEN
      RAISE EXCEPTION '215 ABORTED: pass_leads policy "%" is gone; this file must not have changed it.', v_name;
    END IF;
  END LOOP;
  FOREACH v_name IN ARRAY ARRAY['Users can insert referrals', 'Users can read own referrals',
                                'Users can view own referrals'] LOOP
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'referrals'
                    AND policyname = v_name) THEN
      RAISE EXCEPTION '215 ABORTED: referrals policy "%" is gone; this file must not have changed it.', v_name;
    END IF;
  END LOOP;

  -- The service role, the only writer of both new things, can still write.
  IF NOT has_table_privilege('service_role', 'public.referrals', 'INSERT')
     OR NOT has_table_privilege('service_role', 'public.pass_leads', 'INSERT') THEN
    RAISE EXCEPTION '215 ABORTED: service_role cannot INSERT referrals or pass_leads.';
  END IF;

  RAISE NOTICE '215: lead referral codes, one credit per referred person, client forgery closed.';
END $$;

-- ── Record this migration as applied ────────────────────────────────────────
INSERT INTO public.migrations_applied (migration, note)
VALUES ('215_t_grow2_referral_loop',
        'T-GROW2: pass_leads.lead_ref_code (+CHECK, unique, server-only); referrals one credit per referred; clients create only code rows')
ON CONFLICT (migration) DO NOTHING;

COMMIT;
